//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamaraApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camara
    {
        public int CamaraId { get; set; }
        public string Serial { get; set; }
        public string Fabricante { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
    }
}
