//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamaraApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public int UsuarioId { get; set; }

        [Required(ErrorMessage = "El campo Nombre es requerido")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El campo Nombre es requerido")]
        public string Apellido { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "El campo Nombre es requerido")]
        public string Correo { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "El campo Nombre es requerido")]
        public string Contraseña { get; set; }
        public string ErrorMessage { get; set; }
    }
}
